server:
  port: 8010

info:
  app:
    # 使用@properties.name@ 取pom中对应标签的值
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@


spring:
  application:
    name: jzp-microservice-consumer-movie


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



