server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                             #指定数据源
    platform: h2                          #指定数据源类型
    schema: classpath:schema.sql          #指定h2数据库建表脚本
    data: classpath:data.sql              #指定h2数据库数据脚本
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
endpoints:
  info:
    enabled: true


#TODO 使用.yaml 格式的配置文件时，需要使用 ${}取值，并且project.artifactId和project.build.sourceEncoding取不到
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@