server:
  port: 8761
eureka:
  client:
    #注册自己到eureka server
    register-with-eureka: false
    #从其他节点的server获取注册信息
    fetch-registry: false
    #eureka server 默认地址，多个地址用","分隔
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  basic:
    #开启基于Http basic的认证
    enabled: true
  user:
    #配置登陆的账号为 user(默认) 密码为 password
    name: user
    password: password